{{- if .Values.configSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pomerium.labels" . | nindent 4 }}
stringData:
  config.yaml: |
{{ include "pomerium.config" . | indent 4 }}
{{- end }}
