{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pomerium.labels" . | nindent 4 }}
stringData:
  sharedSecret: {{ required "config.sharedSecret" .Values.config.sharedSecret | quote }}
  cookieSecret: {{ required "config.cookieSecret" .Values.config.cookieSecret | quote }}
{{- end }}
