apiVersion: v1
kind: Service
metadata:
  name: {{ include "pomerium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pomerium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    {{- include "pomerium.selectorLabels" . | nindent 4 }}
