apiVersion: v1
kind: Service
metadata:
  name: {{ include "dex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
  - name: telemetry
    port: {{ .Values.service.telemetryPort }}
    targetPort: telemetry
    protocol: TCP
  selector:
    {{- include "dex.selectorLabels" . | nindent 4 }}
