#!/usr/bin/env bash
set -euo pipefail

# Registry credentials management script.
# Adds or refreshes Harbor robot account credentials in GitHub repository secrets.
#
# Prerequisites:
#   - harbor.sh must have been run first (creates robot account)
#   - GitHub App credentials must be configured
#
# Usage:
#   tools/k3s/registry-credentials.sh <env-name> <github-repo>
#   tools/k3s/registry-credentials.sh --setup-local
#
# Examples:
#   tools/k3s/registry-credentials.sh dev my-app-repo
#   tools/k3s/registry-credentials.sh --setup-local   # writes ~/nexus-env.sh from current kubectl context

REPO_ROOT="$(cd "$(dirname "$0")"/../.. && pwd)"
# shellcheck disable=SC1091
source "$REPO_ROOT/tools/provision-common.sh"
ENVS_ROOT=$(provision::envs_root)

# --- setup-local mode ---
setup_local() {
  local namespace="${NAMESPACE_NEXUS:-nexus}"
  local envs_root
  envs_root="$(provision::envs_root)"

  # Detect env from current kubectl context
  local current_context
  current_context=$(kubectl config current-context 2>/dev/null || true)
  if [[ -z "$current_context" ]]; then
    echo "ERROR: No kubectl context is currently set." >&2
    exit 1
  fi

  local env_name=""
  for d in "$envs_root"/*/env.properties; do
    local candidate
    candidate=$(basename "$(dirname "$d")")
    if [[ "$current_context" == *"$candidate"* ]]; then
      env_name="$candidate"
      break
    fi
  done

  if [[ -z "$env_name" ]]; then
    echo "ERROR: Could not match kubectl context '${current_context}' to any known env." >&2
    echo "Known envs:" >&2
    for d in "$envs_root"/*/env.properties; do
      echo "  $(basename "$(dirname "$d")")" >&2
    done
    exit 1
  fi

  # Load env properties (sets HOSTNAME etc.)
  # shellcheck disable=SC1090
  source "$envs_root/${env_name}/env.properties"

  local nexus_registry="nexus-api.${HOSTNAME}"

  echo "[setup-local] Context: ${current_context} → env: ${env_name}"
  echo "[setup-local] Fetching Nexus credentials from ${namespace}/nexus-deployment-credentials..."

  if ! kubectl get ns "$namespace" >/dev/null 2>&1; then
    echo "ERROR: Namespace '${namespace}' not found in current cluster." >&2
    exit 1
  fi

  if ! kubectl -n "$namespace" get secret nexus-deployment-credentials >/dev/null 2>&1; then
    echo "ERROR: Secret nexus-deployment-credentials not found in namespace '${namespace}'." >&2
    exit 1
  fi

  local nexus_user nexus_pass
  nexus_user=$(kubectl -n "$namespace" get secret nexus-deployment-credentials -o jsonpath='{.data.username}' | base64 -d)
  nexus_pass=$(kubectl -n "$namespace" get secret nexus-deployment-credentials -o jsonpath='{.data.password}' | base64 -d)

  if [[ -z "$nexus_user" || -z "$nexus_pass" ]]; then
    echo "ERROR: Nexus credentials are empty." >&2
    exit 1
  fi

  local out="$HOME/nexus-env.sh"
  cat > "$out" <<EOF
#!/bin/zsh
# Generated by registry-credentials.sh --setup-local
# kubectl context: ${current_context}
CONTEXT=${env_name}

export NEXUS_USERNAME=${nexus_user}
export NEXUS_PASSWORD=${nexus_pass}
export NEXUS_REGISTRY=${nexus_registry}

launchctl setenv NEXUS_USERNAME ${nexus_user}
launchctl setenv NEXUS_PASSWORD ${nexus_pass}
launchctl setenv NEXUS_REGISTRY ${nexus_registry}
EOF
  chmod +x "$out"
  echo "[setup-local] Written ${out}"
  echo "[setup-local] Source it with: source ~/nexus-env.sh"
  exit 0
}

if [[ "${1:-}" == "--setup-local" ]]; then
  setup_local
fi

# --- Parse arguments ---
if [[ -z "${1:-}" || -z "${2:-}" ]]; then
  echo "Usage: $0 <env-name> <github-repo>" >&2
  echo "       $0 --setup-local" >&2
  echo "" >&2
  echo "Examples:" >&2
  echo "  $0 dev my-app-repo" >&2
  echo "  $0 --setup-local            # writes ~/nexus-env.sh from current kubectl context" >&2
  echo "" >&2
  echo "GitHub mode configures Harbor and Nexus credentials as GitHub secrets:" >&2
  echo "  HARBOR_USERNAME - Robot account username" >&2
  echo "  HARBOR_PASSWORD - Robot account password" >&2
  echo "  NEXUS_USERNAME  - Nexus deployment user" >&2
  echo "  NEXUS_PASSWORD  - Nexus deployment password" >&2
  echo "" >&2
  exit 1
fi

ENV_NAME="$1"
GITHUB_REPO="$2"

if provision::load_env "$ENV_NAME"; then
  shift 2
else
  echo "ERROR: Environment '$ENV_NAME' not found (envs/$ENV_NAME/env.properties missing)." >&2
  exit 1
fi

# --- Validation ---
need() { command -v "$1" >/dev/null 2>&1 || { echo "Missing $1" >&2; exit 1; }; }
need kubectl
need curl
need jq
need openssl

if ! command -v gh >/dev/null 2>&1; then
  err "gh CLI is required but not installed"
  err "Install with: brew install gh"
  exit 1
fi

if ! provision::require_tools; then
  exit 1
fi

# Validate kubectl context matches environment
if ! provision::validate_kubectl_context; then
  exit 1
fi

# --- Logging helpers ---
log() { echo "[registry-creds] $*"; }
info() { echo "[registry-creds:info] $*"; }
warn() { echo "[registry-creds:warn] $*" >&2; }
err() { echo "[registry-creds:error] $*" >&2; }

# --- Config defaults ---
NAMESPACE_HARBOR="${NAMESPACE_HARBOR:-harbor}"
NAMESPACE_NEXUS="${NAMESPACE_NEXUS:-nexus}"

log "Configuring Harbor credentials for GitHub repository: ${GITHUB_REPO}"

# ============================================================================
# Step 1: Retrieve Harbor robot credentials
# ============================================================================

log "=== Step 1: Retrieve Harbor Robot Credentials ==="

if ! kubectl get ns "$NAMESPACE_HARBOR" >/dev/null 2>&1; then
  err "Namespace ${NAMESPACE_HARBOR} not found. Run registry.sh first."
  exit 1
fi

if ! kubectl -n "$NAMESPACE_HARBOR" get secret harbor-robot-runner >/dev/null 2>&1; then
  err "Harbor robot credentials not found in ${NAMESPACE_HARBOR}/harbor-robot-runner"
  err "Run registry.sh first to create the robot account:"
  err "  tools/k3s/registry.sh ${ENV_NAME}"
  exit 1
fi

HARBOR_USERNAME=$(kubectl -n "$NAMESPACE_HARBOR" get secret harbor-robot-runner -o jsonpath='{.data.username}' | base64 -d)
HARBOR_PASSWORD=$(kubectl -n "$NAMESPACE_HARBOR" get secret harbor-robot-runner -o jsonpath='{.data.password}' | base64 -d)

if [[ -z "$HARBOR_USERNAME" || -z "$HARBOR_PASSWORD" ]]; then
  err "Failed to retrieve Harbor robot credentials from secret"
  exit 1
fi

info "✓ Retrieved Harbor robot credentials"
info "  Username: ${HARBOR_USERNAME}"
info "  Password: ${HARBOR_PASSWORD:0:10}..."

# ============================================================================
# Step 2: Get GitHub App credentials and generate token
# ============================================================================

log "=== Step 2: Authenticate with GitHub ==="

app_file="$ENVS_ROOT/shared/secrets.plain/github-app-credentials.yaml"
if [[ ! -f "$app_file" ]]; then
  err "GitHub App credentials file not found: $app_file"
  exit 1
fi

gh_app_id=$(provision::yaml_get "$app_file" .stringData.githubAppID)
gh_app_private_key=$(provision::yaml_get "$app_file" .stringData.githubAppPrivateKey)

if [[ -z "$gh_app_id" || -z "$gh_app_private_key" ]]; then
  err "GitHub App credentials incomplete in github-app-credentials.yaml"
  exit 1
fi

# Get GitHub organization from OAuth credentials
oauth_file="$ENVS_ROOT/${ENV_NAME}/secrets.plain/github-oauth-credentials.yaml"
if [[ ! -f "$oauth_file" ]]; then
  err "GitHub OAuth credentials file not found: $oauth_file"
  exit 1
fi

github_org=$(provision::yaml_get "$oauth_file" .stringData.githubOrg)

if [[ -z "$github_org" ]]; then
  err "GitHub organization not found in github-oauth-credentials.yaml"
  exit 1
fi

info "GitHub organization: ${github_org}"
info "Target repository: ${github_org}/${GITHUB_REPO}"

# Generate JWT and get installation token
info "Generating GitHub App token..."
gh_jwt=$(provision::github_app_mint_jwt "$gh_app_id" "$gh_app_private_key")

gh_install_id=$(provision::yaml_get "$app_file" .stringData.githubAppInstallationID)

if [[ -z "$gh_install_id" ]]; then
  err "GitHub App installation ID not found in github-app-credentials.yaml"
  exit 1
fi

gh_token_response=$(curl -sS -X POST \
  -H "Authorization: Bearer ${gh_jwt}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/app/installations/${gh_install_id}/access_tokens")

gh_token=$(echo "$gh_token_response" | jq -r '.token // empty')

if [[ -z "$gh_token" || "$gh_token" == "null" ]]; then
  err "Failed to get GitHub App installation token"
  err "Response: ${gh_token_response}"
  exit 1
fi

info "✓ GitHub App token obtained"

# ============================================================================
# Step 3: Validate GitHub App Permissions
# ============================================================================

log "=== Step 3: Validate GitHub App Permissions ==="

# Check if the GitHub App has the required permissions
info "Checking GitHub App permissions..."
app_permissions=$(curl -sS \
  -H "Authorization: Bearer ${gh_jwt}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/app")

app_name=$(echo "$app_permissions" | jq -r '.name // empty')
secrets_permission=$(echo "$app_permissions" | jq -r '.permissions.secrets // empty')

if [[ -n "$app_name" ]]; then
  info "  GitHub App: ${app_name}"
else
  warn "  Could not retrieve GitHub App name"
fi

if [[ "$secrets_permission" == "write" ]]; then
  info "  ✓ Secrets permission: ${secrets_permission}"
elif [[ "$secrets_permission" == "read" ]]; then
  err "  ✗ Secrets permission: ${secrets_permission} (needs 'write')"
  err ""
  err "The GitHub App has read-only access to secrets but needs write access."
  err ""
  err "To fix this, update your GitHub App permissions:"
  err "  1. Go to: https://github.com/organizations/${github_org}/settings/apps"
  err "  2. Click on your GitHub App: ${app_name}"
  err "  3. Go to 'Permissions & events'"
  err "  4. Under 'Repository permissions', set:"
  err "     - Secrets: Read and write"
  err "  5. Click 'Save changes'"
  err "  6. Accept the permission change in your organization"
  err ""
  exit 1
else
  err "  ✗ Secrets permission: ${secrets_permission:-none}"
  err ""
  err "The GitHub App does not have permission to manage repository secrets."
  err ""
  err "To fix this, update your GitHub App permissions:"
  err "  1. Go to: https://github.com/organizations/${github_org}/settings/apps"
  err "  2. Click on your GitHub App: ${app_name}"
  err "  3. Go to 'Permissions & events'"
  err "  4. Under 'Repository permissions', set:"
  err "     - Secrets: Read and write"
  err "  5. Click 'Save changes'"
  err "  6. Accept the permission change in your organization"
  err ""
  err "After updating permissions, the organization owner must approve the changes."
  err ""
  exit 1
fi

info "✓ GitHub App has required permissions"

# ============================================================================
# Step 4: Verify repository exists
# ============================================================================

log "=== Step 4: Verify Repository ==="

repo_check=$(curl -sS \
  -H "Authorization: token ${gh_token}" \
  -H "Accept: application/vnd.github+json" \
  -w "\n%{http_code}" \
  "https://api.github.com/repos/${github_org}/${GITHUB_REPO}" 2>&1 || echo -e "\n000")

repo_http_code=$(echo "$repo_check" | tail -n 1)

if [[ "$repo_http_code" != "200" ]]; then
  err "Repository ${github_org}/${GITHUB_REPO} not found or not accessible (HTTP ${repo_http_code})"
  err "Ensure the repository exists and the GitHub App has access to it"
  exit 1
fi

info "✓ Repository ${github_org}/${GITHUB_REPO} verified"

# ============================================================================
# Step 5: Configure GitHub Environment Secrets using gh CLI
# ============================================================================

log "=== Step 5: Configure GitHub Environment Secrets ==="

# Authenticate gh CLI with the installation token
export GH_TOKEN="${gh_token}"

# Create environment first
info "Creating environment '${ENV_NAME}' in repository..."
gh api --method PUT "/repos/${github_org}/${GITHUB_REPO}/environments/${ENV_NAME}" \
  --input - <<< '{}' 2>&1 | grep -v "already exists" || true

info "  ✓ Environment '${ENV_NAME}' ready"

# Set environment secrets using gh CLI
info "Setting HARBOR_USERNAME environment secret..."
if gh secret set HARBOR_USERNAME \
  --repo "${github_org}/${GITHUB_REPO}" \
  --env "${ENV_NAME}" \
  --body "${HARBOR_USERNAME}" 2>&1; then
  info "  ✓ HARBOR_USERNAME configured"
else
  err "  Failed to configure HARBOR_USERNAME"
  unset GH_TOKEN
  exit 1
fi

info "Setting HARBOR_PASSWORD environment secret..."
if gh secret set HARBOR_PASSWORD \
  --repo "${github_org}/${GITHUB_REPO}" \
  --env "${ENV_NAME}" \
  --body "${HARBOR_PASSWORD}" 2>&1; then
  info "  ✓ HARBOR_PASSWORD configured"
else
  err "  Failed to configure HARBOR_PASSWORD"
  unset GH_TOKEN
  exit 1
fi

# =========================================================================
# Step 6: Configure Nexus credentials (if available)
# =========================================================================

log "=== Step 6: Configure Nexus Credentials (optional) ==="

if kubectl get ns "$NAMESPACE_NEXUS" >/dev/null 2>&1 && \
   kubectl -n "$NAMESPACE_NEXUS" get secret nexus-deployment-credentials >/dev/null 2>&1; then
  NEXUS_USERNAME=$(kubectl -n "$NAMESPACE_NEXUS" get secret nexus-deployment-credentials -o jsonpath='{.data.username}' | base64 -d)
  NEXUS_PASSWORD=$(kubectl -n "$NAMESPACE_NEXUS" get secret nexus-deployment-credentials -o jsonpath='{.data.password}' | base64 -d)

  if [[ -n "$NEXUS_USERNAME" && -n "$NEXUS_PASSWORD" ]]; then
    info "Setting NEXUS_USERNAME environment secret..."
    if gh secret set NEXUS_USERNAME \
      --repo "${github_org}/${GITHUB_REPO}" \
      --env "${ENV_NAME}" \
      --body "${NEXUS_USERNAME}" 2>&1; then
      info "  ✓ NEXUS_USERNAME configured"
    else
      warn "  Failed to configure NEXUS_USERNAME"
    fi

    info "Setting NEXUS_PASSWORD environment secret..."
    if gh secret set NEXUS_PASSWORD \
      --repo "${github_org}/${GITHUB_REPO}" \
      --env "${ENV_NAME}" \
      --body "${NEXUS_PASSWORD}" 2>&1; then
      info "  ✓ NEXUS_PASSWORD configured"
    else
      warn "  Failed to configure NEXUS_PASSWORD"
    fi
  else
    warn "Nexus deployment credentials found but values are empty"
  fi
else
  info "Nexus deployment credentials not found in ${NAMESPACE_NEXUS}/nexus-deployment-credentials — skipping"
fi

# Clean up token
unset GH_TOKEN

# ============================================================================
# Summary
# ============================================================================

log "=== Harbor credentials configured successfully ==="
info ""
info "Repository: ${github_org}/${GITHUB_REPO}"
info "Environment: ${ENV_NAME}"
info "Secrets configured:"
info "  ✓ HARBOR_USERNAME (environment secret)"
info "  ✓ HARBOR_PASSWORD (environment secret)"
if kubectl get ns "$NAMESPACE_NEXUS" >/dev/null 2>&1 && kubectl -n "$NAMESPACE_NEXUS" get secret nexus-deployment-credentials >/dev/null 2>&1; then
  info "  ✓ NEXUS_USERNAME (environment secret)"
  info "  ✓ NEXUS_PASSWORD (environment secret)"
else
  info "  - NEXUS_USERNAME/NEXUS_PASSWORD skipped (no nexus-deployment-credentials)"
fi
info ""
info "These secrets can now be used in GitHub Actions workflows:"
info ""
info "  jobs:"
info "    build:"
info "      runs-on: [self-hosted, ${ENV_NAME}] "
info "      environment: ${ENV_NAME}  # Required to access environment secrets"
info "      steps:"
info "        - name: Login to Harbor"
info "          uses: docker/login-action@v3"
info "          with:"
info "            registry: ${HARBOR_HOST:-harbor.example.com}"
info "            username: \${{ secrets.HARBOR_USERNAME }}"
info "            password: \${{ secrets.HARBOR_PASSWORD }}"
info ""

# Get GitHub organization for summary
github_org=$(provision::yaml_get "$oauth_file" .stringData.githubOrg 2>/dev/null || echo "N/A")
