apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nexus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nexus.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: nexus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: "-Xms{{ .Values.jvm.xms }} -Xmx{{ .Values.jvm.xmx }} -XX:MaxDirectMemorySize={{ .Values.jvm.maxDirectMemorySize }} -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (printf "%s-data" (include "nexus.fullname" .)) }}
